=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/templates/armors.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Overriding %condition; from conditions.dtd -->
<!ENTITY % condition "and|or|not|player">

<!ENTITY % conditions.dtd SYSTEM "conditions.dtd"> %conditions.dtd;
<!ENTITY % func "set|add|sub|enchant">

<!-- Root -->
<!ELEMENT list (item)*>

<!-- Item -->
<!ATTLIST item id CDATA #REQUIRED>
<!ATTLIST item name CDATA #REQUIRED>
<!ELEMENT item (cond?,for?)>

<!-- Template -->
<!ELEMENT for (%func;)*>

<!-- Condition -->
<!ATTLIST cond msg CDATA #IMPLIED>
<!ATTLIST cond msgId CDATA #IMPLIED>
<!ATTLIST cond addName (1) #IMPLIED>
<!ELEMENT cond (%condition;)>

<!-- Stat -->
<!ATTLIST set     stat (talisman) #REQUIRED>
<!ATTLIST add     stat (pDef|mDef|maxMp|fireRes|windRes|waterRes|earthRes|holyRes|darkRes) #REQUIRED>
<!ATTLIST sub     stat (rEvas) #REQUIRED>
<!ATTLIST enchant stat (pDef|mDef) #REQUIRED>
<!ATTLIST set     order (0x50) #REQUIRED>
<!ATTLIST add     order (0x10|0x40) #REQUIRED>
<!ATTLIST sub     order (0x10) #REQUIRED>
<!ATTLIST enchant order (0x0C) #REQUIRED>
<!ATTLIST set     val CDATA #REQUIRED>
<!ATTLIST add     val CDATA #REQUIRED>
<!ATTLIST sub     val CDATA #REQUIRED>
<!ATTLIST enchant val CDATA #REQUIRED>
<!ELEMENT set     EMPTY>
<!ELEMENT add     EMPTY>
<!ELEMENT sub     EMPTY>
<!ELEMENT enchant EMPTY>

=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/stats/armor/8900-8999.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../../templates/armors.dtd">
<list>
  <item id="8910" name="Black Feather Mask (Event)">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8911" name="Black Half-Mask (Event)">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8912" name="Single Stem Flower">
    <cond msgId="1518">
      <player sex="1"/>
    </cond>
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8913" name="Butterfly Hairpin">
    <cond msgId="1518">
      <player sex="1"/>
    </cond>
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8914" name="Luxurious Gold Circlet">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8915" name="Luxurious Silver Circlet">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8916" name="Eye Patch">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8917" name="Goddess Circlet">
    <cond msgId="1518">
      <player sex="1"/>
    </cond>
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8918" name="Leather Cap">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8919" name="First Mate's Hat">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8920" name="Angel Halo">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8921" name="Demon Circlet">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8922" name="Pirate Hat">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8923" name="Scar">
    <cond msgId="1518">
      <player sex="0"/>
    </cond>
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8936" name="Santa's Antlers">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8947" name="L2 Day: Rabbit Ears">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8948" name="L2 Day: Little Angel Wings">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8949" name="L2 Day: Fairy Antennae">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8950" name="L2 Day: Feathered Hat">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
  <item id="8951" name="L2 Day: Artisan's Goggles">
    <for>
      <add order="0x10" stat="pDef" val="0"/>
    </for>
  </item>
</list>
