=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/templates/dimensional_gap.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root -->
<!ELEMENT rift (area)+>

<!-- Area -->
<!ATTLIST area type CDATA #REQUIRED>
<!ELEMENT area (room+)>

<!-- Room -->
<!ATTLIST room id CDATA #REQUIRED>
<!ATTLIST room name CDATA #REQUIRED> <!-- not parsed -->
<!ATTLIST room isBossRoom (true|false) #IMPLIED>
<!ELEMENT room (teleport?,spawn*,zone)>

<!-- Teleport -->
<!ATTLIST teleport x CDATA #REQUIRED>
<!ATTLIST teleport y CDATA #REQUIRED>
<!ATTLIST teleport z CDATA #REQUIRED>
<!ELEMENT teleport EMPTY>

<!-- Zone -->
<!ATTLIST zone xMin CDATA #REQUIRED>
<!ATTLIST zone xMax CDATA #REQUIRED>
<!ATTLIST zone yMin CDATA #REQUIRED>
<!ATTLIST zone yMax CDATA #REQUIRED>
<!ATTLIST zone zMin CDATA #REQUIRED>
<!ATTLIST zone zMax CDATA #REQUIRED>
<!ELEMENT zone EMPTY>

<!-- Spawns -->
<!ATTLIST spawn mobId CDATA #REQUIRED>
<!ATTLIST spawn delay CDATA #REQUIRED>
<!ATTLIST spawn count CDATA #REQUIRED>
<!ELEMENT spawn EMPTY>

=== nick1pas/darkMoon/l2jdm-datapack/data/dimensionalRift.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rift SYSTEM "templates/dimensional_gap.dtd">
<rift>
  <area type="0">
    <room id="0" name="Dimensional Rift">
      <!-- Not parsed. Why is it here? <type>Start</type> -->
      <teleport x="-114790" y="-180576" z="-6752"/>
      <zone xMin="-115440" xMax="-114160" yMin="-182160" yMax="-178048" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="1" name="Dimensional Rift">
      <!-- Not parsed. Why is it here? <type>DimensionalRift</type> -->
      <zone xMin="-120576" xMax="-109024" yMin="-187328" yMax="-172880" zMin="-6816" zMax="-6240"/>
    </room>
  </area>
  <area type="1">
    <room id="1" name="Dimensional Rift (Recruit Room 1)">
      <teleport x="-111976" y="-182448" z="-6752"/>
      <!-- Otherworldy Invader Soldier -->
      <spawn mobId="21659" count="2" delay="90"/>
      <!-- Otherwordly Invader Archer -->
      <spawn mobId="21661" count="4" delay="80"/>
      <!-- Otherwordly Invader Soldier -->
      <spawn mobId="21660" count="2" delay="90"/>
      <zone xMin="-112368" xMax="-111584" yMin="-182832" yMax="-182064" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="2" name="Dimensional Rift (Recruit Room 2)">
      <teleport x="-111088" y="-182448" z="-6752"/>
      <!-- Otherworldy Invader Priest -->
      <spawn mobId="21664" count="3" delay="90"/>
      <!-- Otherwordly Invader Shaman -->
      <spawn mobId="21663" count="2" delay="90"/>
      <!-- Otherwordly Invader Elite Soldier -->
      <spawn mobId="21662" count="3" delay="90"/>
      <zone xMin="-111472" xMax="-110704" yMin="-182832" yMax="-182064" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="3" name="Dimensional Rift (Recruit Room 3)">
      <teleport x="-110296" y="-180560" z="-6752"/>
      <!-- Otherworldy Invader Martyrs -->
      <spawn mobId="21666" count="2" delay="86"/>
      <!-- Otherwordly Invader Warrior -->
      <spawn mobId="21667" count="2" delay="86"/>
      <!-- Otherwordly Invader Magus -->
      <spawn mobId="21665" count="2" delay="86"/>
      <zone xMin="-110688" xMax="-109904" yMin="-180944" yMax="-180176" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="4" name="Dimensional Rift (Recruit Room 4)">
      <teleport x="-109416" y="-180560" z="-6752"/>
      <!-- Otherworldy Invader Soldier -->
      <spawn mobId="21668" count="2" delay="101"/>
      <!-- Otherwordly Invader Discipline -->
      <spawn mobId="21669" count="2" delay="101"/>
      <!-- Otherwordly Invader Berserker -->
      <spawn mobId="21670" count="2" delay="101"/>
      <zone xMin="-109808" xMax="-109024" yMin="-180944" yMax="-180176" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="5" name="Dimensional Rift (Recruit Room 5)">
      <teleport x="-113264" y="-181520" z="-6752"/>
      <!-- Otherwordly Invader Food -->
      <spawn mobId="18287" count="6" delay="82"/>
      <!-- Otherwordly Invader Elite Soldier -->
      <spawn mobId="21672" count="3" delay="82"/>
      <!-- Otherwordly Invader Elite Soldier -->
      <spawn mobId="21673" count="3" delay="82"/>
      <zone xMin="-114032" xMax="-112496" yMin="-181968" yMax="-181072" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="6" name="Dimensional Rift (Recruit Room 6)">
      <teleport x="-111592" y="-180560" z="-6752"/>
      <!-- Otherworldy Invader Elite Soldier -->
      <spawn mobId="21675" count="4" delay="52"/>
      <!-- Otherwordly Invader Warrior -->
      <spawn mobId="21676" count="4" delay="52"/>
      <!-- Otherwordly Invader Elite Soldier -->
      <spawn mobId="21674" count="4" delay="52"/>
      <zone xMin="-112368" xMax="-110816" yMin="-181008" yMax="-180112" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="7" name="Dimensional Rift (Recruit Room 7)">
      <teleport x="-109800" y="-182448" z="-6752"/>
      <!-- Otherworldy Invader Elite Soldier -->
      <spawn mobId="21677" count="4" delay="100"/>
      <!-- Otherwordly Invader Elite Soldier -->
      <spawn mobId="21678" count="4" delay="100"/>
      <!-- Otherwordly Invader Food -->
      <spawn mobId="18288" count="4" delay="100"/>
      <zone xMin="-110576" xMax="-109024" yMin="-182896" yMax="-182000" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="8" name="Dimensional Rift (Recruit Room 8)">
      <teleport x="-111592" y="-181520" z="-6752"/>
      <!-- Otherworldy Invader Elite Soldier -->
      <spawn mobId="21679" count="4" delay="137"/>
      <!-- Otherwordly Invader Magus -->
      <spawn mobId="21681" count="4" delay="137"/>
      <!-- Otherwordly Invader Elite Soldier -->
      <spawn mobId="21680" count="4" delay="137"/>
      <zone xMin="-112368" xMax="-110816" yMin="-181968" yMax="-181072" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="9" name="Dimensional Rift (Recruit Room 9)" isBossRoom="true">
      <teleport x="-109912" y="-181520" z="-6752"/>
      <!-- Anakazel -->
      <spawn mobId="25333" count="1" delay="600"/>
      <zone xMin="-110688" xMax="-109136" yMin="-181968" yMax="-181072" zMin="-6816" zMax="-6240"/>
    </room>
  </area>
  <area type="2">
    <room id="1" name="Dimensional Rift (Soldier Room 1)">
      <teleport x="-111976" y="-179624" z="-6752"/>
      <!-- Dimension Invader Soldier -->
      <spawn mobId="21682" count="2" delay="90"/>
      <!-- Dimension Invader Archer -->
      <spawn mobId="21684" count="4" delay="80"/>
      <!-- Dimension Invader Soldier -->
      <spawn mobId="21683" count="2" delay="90"/>
      <zone xMin="-112368" xMax="-111584" yMin="-180016" yMax="-179232" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="2" name="Dimensional Rift (Soldier Room 2)">
      <teleport x="-111088" y="-179624" z="-6752"/>
      <!-- Dimension Invader Priest -->
      <spawn mobId="21687" count="3" delay="90"/>
      <!-- Dimension Invader Shaman -->
      <spawn mobId="21686" count="2" delay="90"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21685" count="3" delay="90"/>
      <zone xMin="-111472" xMax="-110704" yMin="-180016" yMax="-179232" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="3" name="Dimensional Rift (Soldier Room 3)">
      <teleport x="-110296" y="-177744" z="-6752"/>
      <!-- Dimension Invader Martyrs -->
      <spawn mobId="21689" count="2" delay="86"/>
      <!-- Dimension Invader Warrior -->
      <spawn mobId="21690" count="2" delay="86"/>
      <!-- Dimension Invader Magus -->
      <spawn mobId="21688" count="2" delay="86"/>
      <zone xMin="-110688" xMax="-109904" yMin="-178128" yMax="-177360" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="4" name="Dimensional Rift (Soldier Room 4)">
      <teleport x="-109416" y="-177744" z="-6752"/>
      <!-- Dimension Invader Soldier -->
      <spawn mobId="21691" count="2" delay="101"/>
      <!-- Dimension Invader Discipline -->
      <spawn mobId="21692" count="2" delay="101"/>
      <!-- Dimension Invader Berserker -->
      <spawn mobId="21693" count="2" delay="101"/>
      <zone xMin="-109808" xMax="-109024" yMin="-178128" yMax="-177360" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="5" name="Dimensional Rift (Soldier Room 5)">
      <teleport x="-113264" y="-178688" z="-6752"/>
      <!-- Dimension Invader Food -->
      <spawn mobId="18289" count="6" delay="82"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21695" count="3" delay="82"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21696" count="3" delay="82"/>
      <zone xMin="-114032" xMax="-112496" yMin="-179136" yMax="-178240" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="6" name="Dimensional Rift (Soldier Room 6)">
      <teleport x="-111592" y="-177744" z="-6752"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21698" count="4" delay="52"/>
      <!-- Dimension Invader Warrior -->
      <spawn mobId="21699" count="4" delay="52"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21697" count="4" delay="52"/>
      <zone xMin="-112368" xMax="-110816" yMin="-178192" yMax="-177296" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="7" name="Dimensional Rift (Soldier Room 7)">
      <teleport x="-109800" y="-179624" z="-6752"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21700" count="4" delay="100"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21701" count="4" delay="100"/>
      <!-- Dimension Invader Food -->
      <spawn mobId="18290" count="4" delay="100"/>
      <zone xMin="-110576" xMax="-109024" yMin="-180064" yMax="-179168" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="8" name="Dimensional Rift (Soldier Room 8)">
      <teleport x="-111592" y="-178688" z="-6752"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21702" count="4" delay="137"/>
      <!-- Dimension Invader Magus -->
      <spawn mobId="21704" count="4" delay="137"/>
      <!-- Dimension Invader Elite Soldier -->
      <spawn mobId="21703" count="4" delay="137"/>
      <zone xMin="-112368" xMax="-110816" yMin="-179136" yMax="-178240" zMin="-6816" zMax="-6240"/>
    </room>
    <room id="9" name="Dimensional Rift (Soldier Room 9)" isBossRoom="true">
      <!-- Anakazel -->
      <teleport x="-109912" y="-178688" z="-6752"/>
      <spawn mobId="25334" count="1" delay="600"/>
      <zone xMin="-110688" xMax="-109136" yMin="-179136" yMax="-178240" zMin="-6816" zMax="-6240"/>
    </room>
  </area>
  <area type="3">
    <room id="1" name="Dimensional Rift (Officer Room 1)">
      <teleport x="-113872" y="-175824" z="-6752"/>
      <!-- Purgatory Invader Soldier -->
      <spawn mobId="21705" count="2" delay="90"/>
      <!-- Purgatory Invader Archer -->
      <spawn mobId="21707" count="4" delay="80"/>
      <!-- Purgatory Invader Soldier -->
