=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/templates/exchange.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.l2jfree.com"
xmlns="http://www.l2jfree.com"
elementFormDefault="qualified">
<xs:include schemaLocation="base.xsd"/>

<xs:element name="list" type="multisell">
  <xs:unique name="order">
    <xs:selector xpath="*"/>
    <xs:field xpath="@id"/>
  </xs:unique>
</xs:element>

<xs:complexType name="multisell">
  <xs:sequence>
    <xs:element ref="item" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="applyTaxes" type="xs:boolean" default="false"/>
  <xs:attribute name="maintainEnchantment" type="xs:boolean" default="false"/>
</xs:complexType>

<xs:element name="production" type="multisellItem"/>
<xs:element name="ingredient">
  <xs:complexType>
    <xs:complexContent>
      <xs:extension base="multisellItem">
        <xs:attribute name="isTaxIngredient" type="xs:boolean" default="false"/>
        <xs:attribute name="maintainIngredient" type="xs:boolean" default="false"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:element>
<xs:element name="item">
  <xs:complexType>
    <xs:complexContent>
      <xs:extension base="identifiable">
        <xs:sequence>
          <xs:element ref="ingredient" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="production" maxOccurs="unbounded"/>
          <!-- To allow any element variation while retaining sequence -->
          <xs:element ref="ingredient" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:element>

<xs:simpleType name="specialItemId">
  <xs:restriction base="xs:int">
    <xs:enumeration value="-200"/> <!-- Clan Reputation -->
    <xs:enumeration value="-300"/> <!-- Fame -->
  </xs:restriction>
</xs:simpleType>
<xs:simpleType name="multisellItemId">
  <xs:union memberTypes="identAsInt specialItemId"/>
</xs:simpleType>
<xs:complexType name="multisellItem">
  <xs:attribute name="id" type="multisellItemId" use="required"/>
  <xs:attribute name="count" type="countAsLong" use="required"/>
</xs:complexType>

</xs:schema>

=== nick1pas/darkMoon/l2jdm-datapack/data/multisell/323560001.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://www.l2jfree.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.l2jfree.com ../templates/exchange.xsd">
  <item id="1">
    <ingredient id="10327" count="200" />
    <production id="9967" count="1" />
  </item>
  <item id="2">
    <ingredient id="10327" count="200" />
    <production id="9968" count="1" />
  </item>
  <item id="3">
    <ingredient id="10327" count="200" />
    <production id="9969" count="1" />
  </item>
  <item id="4">
    <ingredient id="10327" count="200" />
    <production id="9970" count="1" />
  </item>
  <item id="5">
    <ingredient id="10327" count="200" />
    <production id="9971" count="1" />
  </item>
  <item id="6">
    <ingredient id="10327" count="200" />
    <production id="9972" count="1" />
  </item>
  <item id="7">
    <ingredient id="10327" count="200" />
    <production id="9973" count="1" />
  </item>
  <item id="8">
    <ingredient id="10327" count="200" />
    <production id="9974" count="1" />
  </item>
  <item id="9">
    <ingredient id="10327" count="200" />
    <production id="9975" count="1" />
  </item>
 </list>

=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/multisell/311262515.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Seven Signs - Blacksmith of Mammon - Unseal S80-grade Accesories -->
<list maintainEnchantment="true" xmlns="http://www.l2jfree.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.l2jfree.com ../templates/exchange.xsd">
  <!-- Dynasty Earings  -->
  <item id="1">
    <production id="9455" count="1"/>
    <ingredient id="9452" count="1"/>
    <ingredient id="5575" count="9882489"/>
  </item>
  <!-- Dynasty Necklace  -->
  <item id="2">
    <production id="9456" count="1"/>
    <ingredient id="9453" count="1"/>
    <ingredient id="5575" count="13176652"/>
  </item>
  <!-- Dynasty Rings  -->
  <item id="3">
    <production id="9457" count="1"/>
    <ingredient id="9454" count="1"/>
    <ingredient id="5575" count="6538326"/>
  </item>
  <!-- Masterwork Dynasty Earings -->
  <item id="4">
    <production id="11601" count="1"/>
    <ingredient id="11604" count="1"/>
    <ingredient id="5575" count="9882489"/>
  </item>
  <!-- Masterwork Dynasty Necklace -->
  <item id="5">
    <production id="11599" count="1"/>
    <ingredient id="11602" count="1"/>
    <ingredient id="5575" count="13176652"/>
  </item>
  <!-- Masterwork Dynasty Rings -->
  <item id="6">
    <production id="11600" count="1"/>
    <ingredient id="11603" count="1"/>
    <ingredient id="5575" count="6538326"/>
  </item>
</list>

=== nick1pas/darkMoon/l2jdm-datapack/data/multisell/1235.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Apella Trader -->
<!-- by Demolidor -->
<list applyTaxes="true" xmlns="http://www.l2jfree.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.l2jfree.com ../templates/exchange.xsd">
  <!-- Apella Helm -->
  <item id="1">
    <ingredient id="-200" count="696"/>
    <ingredient id="57" count="1384696" isTaxIngredient="true"/>
    <production id="7860" count="1"/>
  </item>
  <!-- Apella Plate Armor -->
  <item id="2">
    <ingredient id="-200" count="2708"/>
    <ingredient id="57" count="5464522" isTaxIngredient="true"/>
    <production id="7861" count="1"/>
  </item>
  <!-- Apella Gauntlet - Heavy Armor -->
  <item id="3">
    <ingredient id="-200" count="464"/>
    <ingredient id="57" count="923043" isTaxIngredient="true"/>
    <production id="7862" count="1"/>
  </item>
  <!-- Apella Solleret - Heavy Armor -->
  <item id="4">
    <ingredient id="-200" count="464"/>
    <ingredient id="57" count="923043" isTaxIngredient="true"/>
    <production id="7863" count="1"/>
  </item>
  <!-- Apella Brigandine -->
  <item id="5">
    <ingredient id="-200" count="2032"/>
    <ingredient id="57" count="4100130" isTaxIngredient="true"/>
    <production id="7864" count="1"/>
  </item>
  <!-- Apella Leather Gloves - Light Armor -->
  <item id="6">
    <ingredient id="-200" count="464"/>
    <ingredient id="57" count="923043" isTaxIngredient="true"/>
    <production id="7865" count="1"/>
  </item>
  <!-- Apella Boots - Light Armor -->
  <item id="7">
    <ingredient id="-200" count="464"/>
    <ingredient id="57" count="923043" isTaxIngredient="true"/>
    <production id="7866" count="1"/>
  </item>
  <!-- Apella Doublet -->
  <item id="8">
    <ingredient id="-200" count="2032"/>
    <ingredient id="57" count="4100130" isTaxIngredient="true"/>
    <production id="7867" count="1"/>
  </item>
  <!-- Apella Silk Gloves - Robe -->
  <item id="9">
    <ingredient id="-200" count="464"/>
    <ingredient id="57" count="923043" isTaxIngredient="true"/>
    <production id="7868" count="1"/>
  </item>
  <!-- Apella Sandals - Robe -->
  <item id="10">
    <ingredient id="-200" count="464"/>
    <ingredient id="57" count="923043" isTaxIngredient="true"/>
    <production id="7869" count="1"/>
  </item>
  <!-- Improved Apella Helm -->
  <item id="11">
    <ingredient id="-200" count="1046"/>
    <ingredient id="9912" count="26"/>
    <ingredient id="57" count="2087652" isTaxIngredient="true"/>
    <production id="9830" count="1"/>
  </item>
  <!-- Improved Apella Plate Armor -->
  <item id="12">
    <ingredient id="-200" count="4532"/>
    <ingredient id="9912" count="115"/>
    <ingredient id="57" count="9050087" isTaxIngredient="true"/>
    <production id="9831" count="1"/>
  </item>
  <!-- Improved Apella Gauntlet - Heavy Armor -->
  <item id="13">
    <ingredient id="-200" count="697"/>
    <ingredient id="9912" count="18"/>
    <ingredient id="57" count="1391661" isTaxIngredient="true"/>
    <production id="9832" count="1"/>
  </item>
  <!-- Improved Apella Solleret - Heavy Armor -->
  <item id="14">
    <ingredient id="-200" count="697"/>
    <ingredient id="9912" count="18"/>
    <ingredient id="57" count="1391661" isTaxIngredient="true"/>
    <production id="9833" count="1"/>
  </item>
  <!-- Improved Apella Brigandine -->
  <item id="15">
    <ingredient id="-200" count="3399"/>
    <ingredient id="9912" count="86"/>
    <ingredient id="57" count="6788043" isTaxIngredient="true"/>
    <production id="9834" count="1"/>
  </item>
  <!-- Improved Apella Leather Gloves - Light Armor -->
  <item id="16">
    <ingredient id="-200" count="697"/>
    <ingredient id="9912" count="18"/>
    <ingredient id="57" count="1391661" isTaxIngredient="true"/>
    <production id="9835" count="1"/>
  </item>
  <!-- Improved Apella Boots - Light Armor -->
  <item id="17">
    <ingredient id="-200" count="697"/>
    <ingredient id="9912" count="18"/>
    <ingredient id="57" count="1391661" isTaxIngredient="true"/>
    <production id="9836" count="1"/>
  </item>
  <!-- Improved Apella Doublet -->
  <item id="18">
    <ingredient id="-200" count="3399"/>
    <ingredient id="9912" count="86"/>
    <ingredient id="57" count="6788043" isTaxIngredient="true"/>
    <production id="9837" count="1"/>
  </item>
  <!-- Improved Apella Silk Gloves - Robe -->
  <item id="19">
    <ingredient id="-200" count="697"/>
    <ingredient id="9912" count="18"/>
    <ingredient id="57" count="1391661" isTaxIngredient="true"/>
    <production id="9838" count="1"/>
  </item>
  <!-- Improved Apella Sandals - Robe -->
  <item id="20">
    <ingredient id="-200" count="697"/>
    <ingredient id="9912" count="18"/>
    <ingredient id="57" count="1391661" isTaxIngredient="true"/>
    <production id="9839" count="1"/>
  </item>
</list>
