=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/templates/zones.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Overriding %condition; from conditions.dtd -->
<!ENTITY % condition "and|or|not|player|game">

<!ENTITY % conditions.dtd SYSTEM "conditions.dtd"> %conditions.dtd;

<!-- Root -->
<!ELEMENT list (zone)*>

<!-- Zone -->
<!ATTLIST zone enabled (true|false) #IMPLIED>
<!ATTLIST zone id CDATA #REQUIRED>
<!ATTLIST zone name CDATA #REQUIRED>
<!ATTLIST zone type (Arena|Boss|CastleTeleport|Castle|Clanhall|CoreBarrier|Damage|Danger|DefenderSpawn|Dynamic|Fishing|Fort|HeadQuarters|Jail|Mothertree|NoHQ|Pagan|Regeneration|Script|SiegeDanger|Siege|Stadium|Town|Water) #IMPLIED>
<!ELEMENT zone (entity?,instance?,msg?,settings?,skill?,restart_chaotic*,restart_owner*,shape+,cond?)>

<!-- Entity -->
<!ATTLIST entity castleId CDATA #IMPLIED>
<!ATTLIST entity clanhallId CDATA #IMPLIED>
<!ATTLIST entity fortId CDATA #IMPLIED>
<!ATTLIST entity townId CDATA #IMPLIED>
<!ELEMENT entity EMPTY>

<!-- Instance -->
<!ATTLIST instance instanceName CDATA #REQUIRED>
<!ATTLIST instance instanceGroup (alliance|clan|party) #REQUIRED>
<!ATTLIST instance minPlayers CDATA #IMPLIED>
<!ATTLIST instance maxPlayers CDATA #IMPLIED>
<!ELEMENT instance EMPTY>

<!-- Messages -->
<!ATTLIST msg onEnter CDATA #IMPLIED>
<!ATTLIST msg onExit CDATA #IMPLIED>
<!ELEMENT msg EMPTY>

<!-- Restarts -->
<!ATTLIST restart_chaotic x CDATA #REQUIRED>
<!ATTLIST restart_chaotic y CDATA #REQUIRED>
<!ATTLIST restart_chaotic z CDATA #REQUIRED>
<!ELEMENT restart_chaotic EMPTY>
<!ATTLIST restart_owner x CDATA #REQUIRED>
<!ATTLIST restart_owner y CDATA #REQUIRED>
<!ATTLIST restart_owner z CDATA #REQUIRED>
<!ELEMENT restart_owner EMPTY>

<!-- Shape -->
<!ATTLIST shape type (Cylinder|ExCylinder|Poly|Rect) #REQUIRED>
<!ATTLIST shape zMin CDATA #REQUIRED>
<!ATTLIST shape zMax CDATA #REQUIRED>
<!ATTLIST shape radius CDATA #IMPLIED>
<!ATTLIST shape innerRadius CDATA #IMPLIED>
<!ATTLIST shape outerRadius CDATA #IMPLIED>
<!ELEMENT shape (point+)>
<!-- Point -->
<!ATTLIST point x CDATA #REQUIRED>
<!ATTLIST point y CDATA #REQUIRED>
<!ELEMENT point EMPTY>

<!-- Skill -->
<!ATTLIST skill applyEnter CDATA #IMPLIED>
<!ATTLIST skill applyExit CDATA #IMPLIED>
<!ATTLIST skill removeEnter CDATA #IMPLIED>
<!ATTLIST skill removeExit CDATA #IMPLIED>
<!ELEMENT skill EMPTY>

<!-- Settings -->
<!ATTLIST settings abnormal CDATA #IMPLIED>
<!ATTLIST settings affected (all|npc|pc|playable) #IMPLIED>
<!ATTLIST settings boss (Anakim|Antharas|Baium|Baylor|FourSepulchers|Frintezza|LastImperialTomb|Lilith|Sailren|SunLightRoom|Valakas|VanHalter|Zaken) #IMPLIED>
<!ATTLIST settings buffRepeat (true|false) #IMPLIED>
<!ATTLIST settings exitOnDeath (true|false) #IMPLIED>
<!ATTLIST settings hpDamage CDATA #IMPLIED>
<!ATTLIST settings landing (true|false) #IMPLIED>
<!ATTLIST settings mpDamage CDATA #IMPLIED>
<!ATTLIST settings noEscape (true|false) #IMPLIED>
<!ATTLIST settings noHeal (true|false) #IMPLIED>
<!ATTLIST settings noWyvern (true|false) #IMPLIED>
<!ATTLIST settings noPrivateStore (true|false) #IMPLIED>
<!ATTLIST settings noSummon (true|false) #IMPLIED>
<!ATTLIST settings pvp (Arena|General|Peace) #IMPLIED>
<!ATTLIST settings questZoneId CDATA #IMPLIED>
<!ELEMENT settings EMPTY>

<!-- Condition -->
<!ELEMENT cond (%condition;)>

=== nick1pas/darkMoon/l2jdm-datapack/data/zone/boss.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../templates/zones.dtd">
<list>
  <zone id="1" name="Four Sepulcher" type="Boss">
    <settings boss="FourSepulchers"/>
    <shape type="Rect" zMin="-7225" zMax="-6621">
      <point x="181241" y="-86443"/>
      <point x="192134" y="-84575"/>
    </shape>
    <shape type="Rect" zMin="-7225" zMax="-6621">
      <point x="179551" y="-89844"/>
      <point x="190342" y="-88042"/>
    </shape>
    <shape type="Rect" zMin="-7225" zMax="-6621">
      <point x="172354" y="-86630"/>
      <point x="174073" y="-75565"/>
    </shape>
    <shape type="Rect" zMin="-7225" zMax="-6621">
      <point x="174697" y="-82707"/>
      <point x="176500" y="-71885"/>
    </shape>
  </zone>
  <zone id="2" name="Lair of Zaken" type="Boss">
    <settings boss="Zaken"/>
    <shape type="Rect" zMin="-3775" zMax="-2690">
      <point x="53182" y="216945"/>
      <point x="57311" y="221151"/>
    </shape>
  </zone>
  <zone id="3" name="Lair of Anakim" type="Boss">
    <settings boss="Anakim"/>
    <shape type="Rect" zMin="-5500" zMax="-3895">
      <point x="184008" y="-10681"/>
      <point x="186107" y="-8589"/>
    </shape>
  </zone>
  <zone id="4" name="Lair of Lilith" type="Boss">
    <settings boss="Lilith"/>
    <shape type="Rect" zMin="-5500" zMax="-3895">
      <point x="183986" y="-13716"/>
      <point x="186097" y="-11532"/>
    </shape>
  </zone>
  <zone id="5" name="Lair of Antharas" type="Boss">
    <settings boss="Antharas"/>
    <shape type="Rect" zMin="-8220" zMax="-4870">
      <point x="173439" y="110176"/>
      <point x="187346" y="119469"/>
    </shape>
  </zone>
  <zone id="6" name="Lair of Baium" type="Boss">
    <settings boss="Baium" noWyvern="true"/>
    <shape type="Rect" zMin="10070" zMax="12480">
      <point x="109448" y="10233"/>
      <point x="118547" y="21446"/>
    </shape>
  </zone>
  <zone id="7" name="Lair of Sailren" type="Boss">
    <settings boss="Sailren"/>
    <shape type="Rect" zMin="-1975" zMax="-1944">
      <point x="26095" y="-8084"/>
      <point x="28987" y="-5295"/>
    </shape>
  </zone>
  <zone id="8" name="Sunlight Room" type="Boss">
    <settings boss="SunLightRoom"/>
    <shape type="Rect" zMin="-2952" zMax="-2690">
      <point x="55794" y="219633"/>
      <point x="56789" y="220629"/>
    </shape>
  </zone>
  <zone id="9" name="Lair of Valakas" type="Boss">
    <settings boss="Valakas"/>
    <shape type="Rect" zMin="-1640" zMax="9880">
      <point x="199755" y="-124724"/>
      <point x="224677" y="-103211"/>
    </shape>
  </zone>
  <zone id="10" name="Altar of Sacrifice" type="Boss">
    <settings boss="VanHalter"/>
    <shape type="Rect" zMin="-10730" zMax="-10290">
      <point x="-18176" y="-54972"/>
      <point x="-14614" y="-51620"/>
    </shape>
  </zone>
  <zone id="11" name="Lair of Scarlet van Halisha" type="Boss">
    <settings boss="Frintezza"/>
    <shape type="Cylinder" radius="2100" zMin="-5116" zMax="-2319">
      <point x="174234" y="-88015"/>
    </shape>
  </zone>
  <zone id="12" name="Lair of Baylor" type="Boss">
    <settings boss="Baylor"/>
    <shape type="Cylinder" radius="4000" zMin="-12650" zMax="-12800">
      <point x="153569" y="142075"/>
    </shape>
  </zone>
  <zone id="13" name="Last Imperial Tomb" type="Boss">
    <settings boss="LastImperialTomb" noWyvern="true"/>
    <shape type="Rect" zMin="-5300" zMax="-3600">
      <point x="172176" y="-74106"/>
      <point x="175984" y="-90033"/>
    </shape>
  </zone>
  <zone id="14" name="Core Damage Zone" type="CoreBarrier">
    <settings exitOnDeath="true" hpDamage="200" affected="playable"/>
    <shape type="Poly" zMin="-6519" zMax="-6319">
      <point x="17869" y="108566"/>
      <point x="18071" y="108774"/>
      <point x="18072" y="109060"/>
      <point x="17865" y="109265"/>
      <point x="17580" y="109264"/>
      <point x="17379" y="109062"/>
      <point x="17379" y="108724"/>
      <point x="17584" y="108569"/>
    </shape>
  </zone>
  <zone id="15" name="spore_boss_swamp_poison_zone" type="Danger">
    <settings exitOnDeath="true" buffRepeat="true" affected="playable"/>
    <skill applyEnter="4148,12;4625,12" removeExit="4148;4625"/> <!-- Poison, Swamp -->
    <shape type="Poly" zMin="-4468" zMax="-4118">
      <point x="43084" y="15944"/>
      <point x="45140" y="15816"/>
      <point x="45748" y="17200"/>
      <point x="44504" y="18780"/>
      <point x="43284" y="18952"/>
      <point x="42476" y="18164"/>
      <point x="42480" y="16448"/>
    </shape>
  </zone>
</list>

=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/zone/questZones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../templates/zones.dtd">
<list>
  <zone id="1" type="Script" name="Emerald Square Secret Door 1 (Ram)">
    <settings questZoneId="100000"/>
    <shape type="Poly" zMin="-12000" zMax="-11700">
      <point x="143621" y="142741"/>
      <point x="143720" y="142751"/>
      <point x="143719" y="142764"/>
      <point x="143619" y="142758"/>
    </shape>
  </zone>
  <zone id="2" type="Script" name="Emerald Square Secret Door 2">
    <settings questZoneId="100001"/>
    <shape type="Poly" zMin="-12000" zMax="-11700">
      <point x="144088" y="142435"/>
      <point x="144086" y="142500"/>
      <point x="144070" y="142492"/>
      <point x="144074" y="142425"/>
    </shape>
  </zone>
  <zone id="3" type="Script" name="Emerald Square Secret Door 3">
    <settings questZoneId="100002"/>
    <shape type="Poly" zMin="-12500" zMax="-12000">
      <point x="147791" y="143766" />
      <point x="147802" y="143683" />
      <point x="147817" y="143685" />
      <point x="147804" y="143769" />
    </shape>
  </zone>
  <zone id="4" type="Script" name="Emerald Square Secret Door 4">
    <settings questZoneId="100003"/>
    <shape type="Poly" zMin="-12300" zMax="-12200">
      <point x="149224" y="143694"/>
      <point x="149279" y="143772"/>
      <point x="149272" y="143785"/>
      <point x="149212" y="143705"/>
    </shape>
  </zone>
</list>

=== nick1pas/darkMoon/l2jdm-datapack/data/zone/siege.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../templates/zones.dtd">
<!--
  The effect of these zones is only applied during siege.
  The strength of the effect depends on the adena invested (lvl 1-4).
  The zones affect both attackers and defenders.
  The zones are set up via Chamberlain; when Flame Control Tower dies during siege, the zones cease working.
  During siege, always show the danger area.
-->
<!--
  Smaller castles have _i (inner) and _o (outer), 
  while larger have _e (east) and _w (west),
-->
<list>
  <!-- Gludio -->
  <zone id="1" name="gludio_slow_damage_i" type="SiegeDanger">
    <entity castleId="1"/>
    <settings abnormal="4000" hpDamage="200" mpDamage="100"/>
    <shape type="Rect" zMin="-2650" zMax="-2550">
      <point x="-18250" y="110800"/>
      <point x="-17970" y="111175"/>
    </shape>
  </zone>
  <zone id="2" name="gludio_slow_damage_o" type="SiegeDanger">
    <entity castleId="1"/>
    <settings abnormal="4000" hpDamage="200" mpDamage="100"/>
    <shape type="Rect" zMin="-2570" zMax="-2400">
      <point x="-19215" y="107390"/>
      <point x="-18830" y="107120"/>
    </shape>
  </zone>

  <!-- Dion -->
  <zone id="3" name="dion_slow_damage_i" type="SiegeDanger">
    <entity castleId="2"/>
    <settings abnormal="4000" hpDamage="200" mpDamage="100"/>
    <shape type="Rect" zMin="-2760" zMax="-2700">
      <point x="22215" y="158950"/>
      <point x="21930" y="158575"/>
    </shape>
  </zone>
  <zone id="4" name="dion_slow_damage_o" type="SiegeDanger">
    <entity castleId="2"/>
    <settings abnormal="4000" hpDamage="200" mpDamage="100"/>
    <shape type="Rect" zMin="-2780" zMax="-2500">
      <point x="23170" y="162350"/>
      <point x="22785" y="162615"/>
    </shape>
  </zone>

  <!-- Giran -->
  <zone id="5" name="giran_slow_damage_i" type="SiegeDanger">
    <entity castleId="3"/>
    <settings abnormal="4000" hpDamage="200" mpDamage="100"/>
    <shape type="Rect" zMin="-2640" zMax="-2570">
      <point x="115115" y="145000"/>
      <point x="114745" y="145235"/>
    </shape>
  </zone>
  <zone id="6" name="giran_slow_damage_o" type="SiegeDanger">
    <entity castleId="3"/>
    <settings abnormal="4000" hpDamage="200" mpDamage="100"/>
    <shape type="Rect" zMin="-2635" zMax="-2500">
      <point x="118540" y="144000"/>
      <point x="118775" y="144380"/>
    </shape>
  </zone>

  <!-- Oren -->
  <zone id="7" name="oren_slow_damage_i" type="SiegeDanger">
    <entity castleId="4"/>
    <settings abnormal="4000" hpDamage="200" mpDamage="100"/>
    <shape type="Rect" zMin="-2335" zMax="-2370">
      <point x="80725" y="37055"/>
      <point x="81200" y="37330"/>
    </shape>
  </zone>
  <zone id="8" name="oren_slow_damage_o" type="SiegeDanger">
    <entity castleId="4"/>
    <settings abnormal="4000" hpDamage="200" mpDamage="100"/>
    <shape type="Rect" zMin="-2370" zMax="-2200">
      <point x="84590" y="36080"/>
      <point x="84860" y="36485"/>
    </shape>
  </zone>

  <!-- Aden -->
  <zone id="9" name="aden_slow_damage_1w" type="SiegeDanger">
    <entity castleId="5"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-496" zMax="-296">
      <point x="145548" y="6669"/>
      <point x="145813" y="6804"/>
    </shape>
  </zone>
  <zone id="10" name="aden_slow_damage_2w" type="SiegeDanger">
    <entity castleId="5"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-496" zMax="-296">
      <point x="145548" y="6797"/>
      <point x="145813" y="6932"/>
    </shape>
  </zone>
  <zone id="11" name="aden_slow_damage_3w" type="SiegeDanger">
    <entity castleId="5"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-496" zMax="-296">
      <point x="145548" y="6925"/>
      <point x="145813" y="7060"/>
    </shape>
  </zone>
  <zone id="12" name="aden_slow_damage_4w" type="SiegeDanger">
    <entity castleId="5"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-528" zMax="-328">
      <point x="145548" y="7053"/>
      <point x="145813" y="7188"/>
    </shape>
  </zone>
  <zone id="13" name="aden_slow_damage_1e" type="SiegeDanger">
    <entity castleId="5"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-528" zMax="-328">
      <point x="149084" y="6685"/>
      <point x="149349" y="6820"/>
    </shape>
  </zone>
  <zone id="14" name="aden_slow_damage_2e" type="SiegeDanger">
    <entity castleId="5"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-528" zMax="-328">
      <point x="149084" y="6813"/>
      <point x="149349" y="6948"/>
    </shape>
  </zone>
  <zone id="15" name="aden_slow_damage_3e" type="SiegeDanger">
    <entity castleId="5"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-528" zMax="-328">
      <point x="149084" y="6941"/>
      <point x="149349" y="7076"/>
    </shape>
  </zone>
  <zone id="16" name="aden_slow_damage_4e" type="SiegeDanger">
    <entity castleId="5"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-560" zMax="-360">
      <point x="149084" y="7069"/>
      <point x="149349" y="7204"/>
    </shape>
  </zone>

  <!-- Innadril -->
  <!-- Retail zones have 30k+ zMax, which is foolish -->
  <zone id="17" name="innadrile_slow_damage_i" type="SiegeDanger">
    <entity castleId="6"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-917" zMax="-717">
      <point x="116166" y="247739"/>
      <point x="115883" y="247355"/>
    </shape>
  </zone>
  <zone id="18" name="innadrile_slow_damage_o" type="SiegeDanger">
    <entity castleId="6"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Rect" zMin="-885" zMax="-685">
      <point x="117124" y="251392"/>
      <point x="116738" y="251125"/>
    </shape>
  </zone>

  <!-- Goddard -->
  <zone id="19" name="godad_slow_damage_e" type="SiegeDanger">
    <entity castleId="7"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Poly" zMin="-1789" zMax="-1489">
      <point x="149235" y="-47768"/>
      <point x="149579" y="-47608"/>
      <point x="149515" y="-47472"/>
      <point x="149169" y="-47634"/>
    </shape>
  </zone>
  <zone id="20" name="godad_slow_damage_w" type="SiegeDanger">
    <entity castleId="7"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Poly" zMin="-1789" zMax="-1439">
      <point x="145352" y="-47607"/>
      <point x="145696" y="-47768"/>
      <point x="145760" y="-47633"/>
      <point x="145415" y="-47471"/>
    </shape>
  </zone>

  <!-- FIXME: Verify sides! -->
  <zone id="21" name="rune_slow_damage_e" type="SiegeDanger">
    <entity castleId="8"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Poly" zMin="500" zMax="900">
      <point x="14089" y="-47869"/>
      <point x="14205" y="-47704"/>
      <point x="13899" y="-47465"/>
      <point x="13792" y="-47637"/>
    </shape>
  </zone>
  <zone id="22" name="rune_slow_damage_w" type="SiegeDanger">
    <entity castleId="8"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Poly" zMin="500" zMax="900">
      <point x="13794" y="-50658"/>
      <point x="13897" y="-50839"/>
      <point x="14204" y="-50610"/>
      <point x="14068" y="-50449"/>
    </shape>
  </zone>

  <!-- FIXME: Verify sides! -->
  <zone id="23" name="schtgart_slow_damage_e" type="SiegeDanger">
    <entity castleId="9"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Poly" zMin="-50" zMax="200">
      <point x="79694" y="-151664"/>
      <point x="79320" y="-151841"/>
      <point x="79320" y="-151694"/>
      <point x="79661" y="-151504"/>
    </shape>
  </zone>
  <zone id="24" name="schtgart_slow_damage_w" type="SiegeDanger">
    <entity castleId="9"/>
    <settings abnormal="4000" hpDamage="200"/>
    <shape type="Poly" zMin="-50" zMax="200">
      <point x="75477" y="-151519"/>
      <point x="75410" y="-151660"/>
      <point x="75801" y="-151840"/>
      <point x="75865" y="-151700"/>
    </shape>
  </zone>
</list>
