=== nick1pas/darkMoon/l2jdm-datapack/data/templates/instances.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.l2jfree.com"
xmlns="http://www.l2jfree.com"
elementFormDefault="qualified">
<xs:include schemaLocation="base.xsd"/>

<xs:element name="instance">
  <xs:complexType>
    <xs:complexContent>
      <xs:extension base="instanceType">
        <xs:all>
          <xs:element name="activityTime" type="timeType" minOccurs="0"/> <!-- Minutes -->
          <xs:element name="allowSummon" type="boolAtrType" minOccurs="0"/>
          <xs:element name="timeDelay" type="timeType" minOccurs="0"/> <!-- Missing handling core-side; hours -->
          <xs:element name="emptyDestroyTime" type="timeType" minOccurs="0"/> <!-- Seconds -->
          <xs:element name="PvPInstance" type="boolAtrType" minOccurs="0"/>
          <xs:element name="returnTeleport" type="coordType" minOccurs="0"/>
          <xs:element name="doorList" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="door" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="spawnList" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="spawn" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="spawnPoint" type="coordType" minOccurs="0"/>
        </xs:all>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:element>

<xs:element name="door">
  <xs:complexType>
    <xs:attribute name="doorId" type="identAsInt" use="required"/>
    <xs:attribute name="open" type="xs:boolean"/>
  </xs:complexType>
</xs:element>
<xs:element name="spawn">
  <xs:complexType>
    <xs:complexContent>
      <xs:extension base="coordType">
        <xs:attribute name="npcId" type="identAsInt" use="required"/>
        <xs:attribute name="heading" type="xs:unsignedShort" use="required"/>
        <xs:attribute name="respawnDelay" type="xs:nonNegativeInteger" default="0"/>
        <xs:attribute name="amount" type="countAsInt" default="1"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:element>

<xs:complexType name="timeType">
  <xs:attribute name="val" type="xs:positiveInteger" use="required"/>
</xs:complexType>
<xs:complexType name="boolAtrType">
  <xs:attribute name="val" type="xs:boolean" use="required"/>
</xs:complexType>
<xs:complexType name="instanceType">
  <xs:complexContent>
    <xs:extension base="nameable">
      <xs:attribute name="template" type="identAsInt"/>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
<xs:complexType name="coordType">
  <xs:attributeGroup ref="coords"/>
</xs:complexType>

</xs:schema>

=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/instances/Kamaloka-39.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Kamaloka-39" xmlns="http://www.l2jfree.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.l2jfree.com ../templates/instances.xsd">
  <activityTime val="45"/>
  <timeDelay val="24"/>
  <allowSummon val="false"/>
  <emptyDestroyTime val="300"/>
  <returnTeleport x="18149" y="146024" z="-3100"/>
  <spawnList>
	<spawn npcId="32496" x="-10857" y="-174902" z="-10946" heading="3355"/> 
  </spawnList>
</instance>

=== nick1pas/darkMoon/l2jdm-datapack/data/instances/DarkCloudMansion.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance template="9" name="Dark Cloud Mansion" xmlns="http://www.l2jfree.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.l2jfree.com ../templates/instances.xsd">
  <activityTime val="30"/>
  <timeDelay val="24"/>
  <allowSummon val="false"/>
  <emptyDestroyTime val="60"/>
  <returnTeleport x="139408" y="150805" z="-3108"/>
  <doorList>
    <door doorId="24230001"/>
    <door doorId="24230002"/>
    <door doorId="24230005"/>
    <door doorId="24230003"/>
    <door doorId="24230004"/>
    <door doorId="24230006"/>
    <door doorId="24230007"/>
    <door doorId="24230008"/>
    <door doorId="24230009"/>
    <door doorId="24230010"/>
    <door doorId="24230011"/>
    <door doorId="24230012"/>
    <door doorId="24230013"/>
  </doorList>
</instance>

=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/instances/TowerOfNaiaRoom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- author hex1r0 -->
<instance name="TowerOfNaiaRoom" xmlns="http://www.l2jfree.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.l2jfree.com ../templates/instances.xsd">
  <emptyDestroyTime val="10"/>
  <allowSummon val="false"/>
  <returnTeleport x="16430" y="244437" z="11618"/>
  <doorList>
    <door doorId="18250001"/>
    <door doorId="18250002"/>
    <door doorId="18250003"/>
    <door doorId="18250004"/>
    <door doorId="18250005"/>
    <door doorId="18250006"/>
    <door doorId="18250007"/>
    <door doorId="18250008"/>
    <door doorId="18250009"/>
    <door doorId="18250010"/>
    <door doorId="18250011"/>
    <door doorId="18250101"/>
    <door doorId="18250013"/>
    <door doorId="18250014"/>
    <door doorId="18250015"/>
    <door doorId="18250102"/>
    <door doorId="18250017"/>
    <door doorId="18250018"/>
    <door doorId="18250019"/>
    <door doorId="18250103"/>
    <door doorId="18250021"/>
    <door doorId="18250022"/>
    <door doorId="18250023"/>
    <door doorId="18250024"/>
    <door doorId="18250025"/>
  </doorList>
</instance>

=== nick1pas/darkMoon/l2jdm-datapack/data/instances/SongOfIceAndFire.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance template="43" name="Pailaka Song of Ice and Fire" xmlns="http://www.l2jfree.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.l2jfree.com ../templates/instances.xsd">
  <activityTime val="60"/>
  <timeDelay val="24"/>
  <allowSummon val="false"/>
  <returnTeleport x="-80609" y="151341" z="-3046"/>
  <spawnList>
    <spawn npcId="32500" x="-53906" y="188200" z="-4667" heading="65163"/>
    <spawn npcId="32492" x="-54822" y="190638" z="-4480" heading="50019"/>
    <spawn npcId="32492" x="-56005" y="190072" z="-4480" heading="16383"/>
    <spawn npcId="18611" x="-55442" y="190340" z="-4480" heading="38942"/>
    <spawn npcId="18611" x="-55744" y="190698" z="-4480" heading="48622"/>
    <spawn npcId="18612" x="-55757" y="190183" z="-4480" heading="35530"/>
    <spawn npcId="18616" x="-57316" y="190091" z="-4518" heading="1405"/>
    <spawn npcId="18611" x="-57340" y="188371" z="-4501" heading="16554"/>
    <spawn npcId="18611" x="-57532" y="188103" z="-4501" heading="9059"/>
    <spawn npcId="18612" x="-57417" y="188232" z="-4501" heading="8789"/>
    <spawn npcId="18611" x="-59088" y="188565" z="-4518" heading="47738"/>
    <spawn npcId="18611" x="-59173" y="187984" z="-4518" heading="61584"/>
    <spawn npcId="18612" x="-59361" y="188277" z="-4518" heading="30750"/>
    <spawn npcId="18613" x="-60379" y="188255" z="-4518" heading="64884"/>
    <spawn npcId="32492" x="-60587" y="188263" z="-4517" heading="64590"/>
    <spawn npcId="18611" x="-55643" y="188438" z="-4518" heading="12242"/>
    <spawn npcId="18611" x="-55720" y="188010" z="-4518" heading="42065"/>
    <spawn npcId="18612" x="-56110" y="188291" z="-4518" heading="27912"/>
    <spawn npcId="18613" x="-55348" y="188292" z="-4518" heading="32767"/>
    <spawn npcId="32492" x="-54435" y="188274" z="-4518" heading="32132"/>
    <spawn npcId="18611" x="-58336" y="186101" z="-4517" heading="65309"/>
    <spawn npcId="18613" x="-58768" y="186132" z="-4524" heading="242"/>
    <spawn npcId="18611" x="-58497" y="185367" z="-4517" heading="42593"/>
    <spawn npcId="18612" x="-58694" y="185149" z="-4529" heading="33971"/>
    <spawn npcId="32492" x="-59089" y="185351" z="-4524" heading="800"/>
    <spawn npcId="32507" x="-57091" y="185704" z="-4518" heading="32452"/>
    <spawn npcId="18610" x="-56171" y="185858" z="-4518" heading="33735"/>
    <spawn npcId="18616" x="-57737" y="183541" z="-4518" heading="6316"/>
    <spawn npcId="18611" x="-55479" y="183389" z="-4518" heading="29376"/>
    <spawn npcId="18611" x="-54984" y="183585" z="-4518" heading="29490"/>
    <spawn npcId="18612" x="-55498" y="183752" z="-4518" heading="27951"/>
    <spawn npcId="18613" x="-55224" y="183431" z="-4518" heading="28717"/>
    <spawn npcId="18611" x="-55785" y="182587" z="-4518" heading="17864"/>
    <spawn npcId="18611" x="-55778" y="181937" z="-4518" heading="49172"/>
    <spawn npcId="32492" x="-55778" y="180662" z="-4524" heading="16001"/>
    <spawn npcId="18613" x="-55964" y="184468" z="-4518" heading="64590"/>
    <spawn npcId="18612" x="-55661" y="184453" z="-4518" heading="34065"/>
    <spawn npcId="32492" x="-56419" y="184457" z="-4518" heading="297"/>
    <spawn npcId="18611" x="-54966" y="181956" z="-4518" heading="16737"/>
    <spawn npcId="18612" x="-54974" y="181264" z="-4517" heading="16770"/>
    <spawn npcId="32492" x="-54971" y="180645" z="-4524" heading="16638"/>
    <spawn npcId="18611" x="-54905" y="184711" z="-4517" heading="20288"/>
    <spawn npcId="18613" x="-54733" y="185187" z="-4524" heading="43893"/>
    <spawn npcId="32492" x="-54879" y="185238" z="-4524" heading="48284"/>
    <spawn npcId="18609" x="-53863" y="181482" z="-4558" heading="16696"/>
    <spawn npcId="18612" x="-53950" y="181300" z="-4558" heading="11769"/>
    <spawn npcId="18613" x="-53757" y="181317" z="-4558" heading="18804"/>
    <spawn npcId="18612" x="-53861" y="181836" z="-4558" heading="12803"/>
    <spawn npcId="18620" x="-53582" y="185022" z="-4619" heading="64590"/>
    <spawn npcId="18613" x="-53469" y="184846" z="-4630" heading="64898"/>
    <spawn npcId="18613" x="-53417" y="185260" z="-4630" heading="58498"/>
    <spawn npcId="32507" x="-53854" y="179303" z="-4644" heading="11446"/>
    <spawn npcId="18614" x="-55692" y="179289" z="-4818" heading="359"/>
    <spawn npcId="18615" x="-56345" y="179394" z="-4818" heading="64817"/>
    <spawn npcId="18614" x="-56428" y="179181" z="-4818" heading="62683"/>
    <spawn npcId="18614" x="-56768" y="179386" z="-4818" heading="62400"/>
    <spawn npcId="18616" x="-59369" y="179177" z="-4818" heading="2015"/>
    <spawn npcId="32507" x="-60201" y="181339" z="-4818" heading="61234"/>
    <spawn npcId="18614" x="-59088" y="181447" z="-4818" heading="40747"/>
    <spawn npcId="18615" x="-59523" y="181284" z="-4818" heading="39156"/>
    <spawn npcId="18614" x="-59977" y="181597" z="-4819" heading="53628"/>
    <spawn npcId="18608" x="-61415" y="181418" z="-4818" heading="63852"/>
    <spawn npcId="32493" x="-61425" y="182635" z="-4818" heading="65027"/>
    <spawn npcId="18614" x="-61246" y="182761" z="-4818" heading="52912"/>
    <spawn npcId="18614" x="-61921" y="182779" z="-4818" heading="32047"/>
    <spawn npcId="18615" x="-61700" y="182440" z="-4818" heading="62310"/>
    <spawn npcId="18615" x="-62650" y="182217" z="-4818" heading="49511"/>
    <spawn npcId="18615" x="-62648" y="181411" z="-4818" heading="49231"/>
    <spawn npcId="32493" x="-62648" y="181033" z="-4818" heading="14568"/>
    <spawn npcId="18615" x="-62647" y="180070" z="-4818" heading="49207"/>
    <spawn npcId="32493" x="-61654" y="179659" z="-4818" heading="31654"/>
    <spawn npcId="18614" x="-61285" y="179728" z="-4818" heading="30212"/>
    <spawn npcId="18614" x="-61985" y="179837" z="-4818" heading="15368"/>
    <spawn npcId="18615" x="-61786" y="179408" z="-4819" heading="20623"/>
    <spawn npcId="32493" x="-55678" y="181341" z="-4818" heading="32546"/>
    <spawn npcId="18614" x="-56547" y="181333" z="-4807" heading="32396"/>
    <spawn npcId="18615" x="-57013" y="181320" z="-4807" heading="33065"/>
    <spawn npcId="18614" x="-57616" y="181354" z="-4807" heading="32292"/>
    <spawn npcId="18615" x="-58413" y="184465" z="-4818" heading="38857"/>
    <spawn npcId="32493" x="-58250" y="184298" z="-4818" heading="30509"/>
    <spawn npcId="18614" x="-58894" y="182709" z="-4818" heading="35426"/>
    <spawn npcId="18615" x="-59012" y="182381" z="-4818" heading="45549"/>
    <spawn npcId="18615" x="-58765" y="182190" z="-4818" heading="62289"/>
    <spawn npcId="18614" x="-58548" y="182613" z="-4818" heading="12219"/>
    <spawn npcId="32493" x="-58586" y="182450" z="-4818" heading="30915"/>
    <spawn npcId="18615" x="-59504" y="183787" z="-4818" heading="45996"/>
    <spawn npcId="18615" x="-59499" y="184397" z="-4818" heading="20522"/>
    <spawn npcId="18614" x="-59495" y="183221" z="-4818" heading="37757"/>
    <spawn npcId="18607" x="-61863" y="183571" z="-4824" heading="3204"/>
    <spawn npcId="18616" x="-59676" y="186186" z="-4818" heading="16196"/>
    <spawn npcId="18615" x="-57152" y="186111" z="-4818" heading="33022"/>
    <spawn npcId="18615" x="-56976" y="186479" z="-4818" heading="33494"/>
    <spawn npcId="18614" x="-57309" y="186320" z="-4818" heading="37221"/>
    <spawn npcId="32493" x="-57361" y="186271" z="-4972" heading="945"/>
    <spawn npcId="32493" x="-57017" y="186267" z="-4972" heading="32767"/>
    <spawn npcId="18614" x="-57191" y="186253" z="-4973" heading="17216"/>
    <spawn npcId="18615" x="-57184" y="186579" z="-4972" heading="17699"/>
    <spawn npcId="18615" x="-57194" y="185901" z="-4973" heading="38795"/>
    <spawn npcId="18614" x="-54897" y="186785" z="-4818" heading="38404"/>
    <spawn npcId="18614" x="-55211" y="186396" z="-4818" heading="41103"/>
    <spawn npcId="18615" x="-55344" y="186499" z="-4818" heading="25894"/>
    <spawn npcId="18614" x="-55199" y="186649" z="-4818" heading="63813"/>
    <spawn npcId="18615" x="-54972" y="186571" z="-4818" heading="10584"/>
  </spawnList>
</instance>
