=== nick1pas/darkMoon/L2DM_DataPack_IL/data/stats/weapon/weapons.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	L2J XML armors DTD

	This defines a simple and consistent way of creating a namespace
	of weapons objects, managed by L2J

	Each "item" element in this document defines a weapon item.

	XML documents that conform to this DTD should declare the following doctype:

	<!DOCTYPE list SYSTEM "weapons.dtd">
-->

<!--
	The document root. A document can contain item definitions only.
-->
<!ELEMENT list (item)*>


<!--
	The document item. A item can contain "for, add, sub, div, set or mul" element.
	add, sub, div and mul can modify a stat
-->
<!ELEMENT item (for|add|sub|div|mul|set)*>

<!--
	The document for. A item can contain "add,mull,enchant,sub and div" element
-->
<!ELEMENT for (add|mul|enchant|sub|div|set|skill)*>


<!--
	add, div, sub, mul could coutain condition "and" and "or"
-->
<!ELEMENT add (and|or)*>
<!ELEMENT div (and|or)*>
<!ELEMENT sub (and|or)*>
<!ELEMENT mul (and|or)*>
<!ELEMENT set (and|or)*>

<!--
	enchant are empty
-->
<!ELEMENT enchant EMPTY>

<!--
	and conditions could specified use of an item or his kind, the target or a not condition
-->
<!ELEMENT and (using|target|not|player|game)*>
<!--
	the "not" condition could specified the use of an item
-->
<!ELEMENT not (using)*>
<!--
	the "or" could specified several "and" condition
-->
<!ELEMENT or (and)*>
<!--
	target specified the type of the target (dagger ?)
-->
<!ELEMENT target EMPTY>

<!ELEMENT player EMPTY>

<!ELEMENT skill EMPTY>
<!ELEMENT game EMPTY>

<!--
	using specified the item, the position on paperdoll and the level of enchant
	(should used three attributes instead of one...)
-->
<!ELEMENT using EMPTY>

<!--
 id and name are mandatory for an item
-->
<!ATTLIST item id CDATA #REQUIRED>
<!ATTLIST item name CDATA #REQUIRED>

<!--
 all operations must specified val order and stat 
-->
<!ATTLIST set val CDATA #REQUIRED>
<!ATTLIST set order CDATA #REQUIRED>
<!ATTLIST set stat CDATA #REQUIRED>

<!ATTLIST add val CDATA #REQUIRED>
<!ATTLIST add order CDATA #REQUIRED>
<!ATTLIST add stat CDATA #REQUIRED>

<!ATTLIST div val CDATA #REQUIRED>
<!ATTLIST div order CDATA #IMPLIED>
<!ATTLIST div stat CDATA #REQUIRED>

<!ATTLIST sub val CDATA #REQUIRED>
<!ATTLIST sub order CDATA #IMPLIED>
<!ATTLIST sub stat CDATA #REQUIRED>

<!ATTLIST mul val CDATA #REQUIRED>
<!ATTLIST mul order CDATA #IMPLIED>
<!ATTLIST mul stat CDATA #REQUIRED>

<!ATTLIST enchant val CDATA #REQUIRED>
<!ATTLIST enchant order CDATA #IMPLIED>
<!ATTLIST enchant stat CDATA #REQUIRED>

<!--
 A weapon could launch a skill under some conditions
 onCrit = 0 or 1 if skill is on critical hits
 onCast = 0 or 1 if skill is launch on casting
 id is the id of the skill
 lvl is the level of the skill
 chance is the percentage of success to launch the skills (but not the percentage
 of success of the skill)
-->
<!ATTLIST skill onCrit (0|1) #IMPLIED>
<!ATTLIST skill onCast (0|1) #IMPLIED>
<!ATTLIST skill id CDATA #REQUIRED>
<!ATTLIST skill lvl CDATA #REQUIRED>
<!ATTLIST skill chance CDATA #IMPLIED>

<!--
 ???
-->
<!ATTLIST game chance CDATA #IMPLIED>


<!--
 the use of an item could be specified for a kind of item or a dependency with another item
-->
<!ATTLIST using slotitem CDATA #IMPLIED>
<!ATTLIST using kind CDATA #IMPLIED>

<!--
 
-->
<!ATTLIST target using CDATA #IMPLIED>

<!--
 Modification of stats could be conditionned by hp or position of the player
-->
<!ATTLIST player behind (True | False) #IMPLIED>
<!ATTLIST player hp CDATA #IMPLIED>

=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/stats/weapon/2900-2999.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../../templates/weapons.dtd">
<list>
  <item id="2915" name="Old Knight Sword">
    <for>
      <set val="24" order="0x08" stat="pAtk"/>
      <set val="17" order="0x08" stat="mAtk"/>
      <set val="8" order="0x08" stat="rCrit"/>
      <add val="0" order="0x10" stat="accCombat"/>
      <set val="379" order="0x08" stat="pAtkSpd"/>
      <enchant val="0" order="0x0C" stat="pAtk"/>
      <enchant val="0" order="0x0C" stat="mAtk"/>
    </for>
  </item>
</list>

=== nick1pas/darkMoon/L2DM_DataPack_IL/data/stats/weapon/8300-8399.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "weapons.dtd">
<list>
<item id='8350' name="chrono_maracas">
  <for>
    <set val='1' order='0x08' stat='pAtk' />
    <set val='5' order='0x08' stat='mAtk' />
    <set val='8' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
</list>

=== nick1pas/darkMoon/L2DM_DataPack_IL/data/stats/weapon/8200-8299.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "weapons.dtd">
<list>
<item id='8203' name="Monster Only(benom_sword)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8204' name="Monster OnlyMonster Only(follower_of_frintessa_calibur)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8205' name="Monster Only(heretic_priest_sickle)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8206' name="Monster Only(heretic_priest_sword)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8207' name="Monster Only(heretic_privates_axe)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8208' name="Monster Only(heretic_privates_staff)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8209' name="Monster Only(lidia_von_helmann_sword)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8210' name="Monster Only(monk_warrior_shield)">
  <for>
    <sub val='8' order='0x40' stat='rEvas' />
    <set val='230' order='0x08' stat='pDef' />
	<set val='230' order='0x08' stat='sDef' />
    <set val='20' order='0x08' stat='rShld' />
    <enchant val='0' order='0x0C' stat='pDef' />
	<enchant val='0' order='0x0C' stat='sDef' />
  </for>
</item>
<item id='8211' name="Monster Only(monk_warrior_sword)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8212' name="Monster Only(solina_brother_mace)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8213' name="Monster Only(solina_father_mace)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8214' name="Monster Only(solina_priest_pole)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <set val='66' order='0x08' stat='pAtkRange'/>
    <add val='0' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8215' name="Monster Only(zombie_enlisted_man_sword)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='0' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8216' name="Monster Only(zombie_enlisted_man_sword)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='4' order='0x08' stat='rCrit' />
    <add val='4' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8217' name="Monster Only(zombie_gateguard_spear)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='8' order='0x08' stat='rCrit' />
    <set val='66' order='0x08' stat='pAtkRange'/>
    <add val='0' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8218' name="Monster Only(zombie_laborer_axe)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='4' order='0x08' stat='rCrit' />
    <add val='4' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8219' name="Monster Only(zombie_laborer_sword)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='8' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8220' name="Monster Only(apostle_grail_bow)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='12' order='0x08' stat='rCrit' />
    <add val='-3' order='0x40' stat='accCombat' />
    <set val='293' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8221' name="Monster Only(apostle_grail_spear)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='8' order='0x08' stat='rCrit' />
    <set val='66' order='0x08' stat='pAtkRange'/>
    <add val='-3' order='0x40' stat='accCombat' />
    <set val='325' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
<item id='8222' name="Monster Only(follower_of_frintessa_tran_calibur)">
  <for>
    <set val='0' order='0x08' stat='pAtk' />
    <set val='10' order='0x08' stat='mAtk' />
    <set val='8' order='0x08' stat='rCrit' />
    <add val='0' order='0x40' stat='accCombat' />
    <set val='379' order='0x08' stat='pAtkSpd' />
    <enchant val='0' order='0x0C' stat='pAtk' />
    <enchant val='0' order='0x0C' stat='mAtk' />
  </for>
</item>
</list>

=== nick1pas/darkMoon/trunk/l2jdm-datapack/data/stats/weapon/12700-12799.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../../templates/weapons.dtd">
<list>
  <item id="12793" name="O Stick - 30 day limited period">
    <for>
      <set val="1" order="0x08" stat="pAtk"/>
      <set val="1" order="0x08" stat="mAtk"/>
      <set val="8" order="0x08" stat="rCrit"/>
      <add val="0" order="0x10" stat="accCombat"/>
      <set val="379" order="0x08" stat="pAtkSpd"/>
    </for>
  </item>
  <item id="12794" name="X Stick - 30 day limited period">
    <for>
      <set val="1" order="0x08" stat="pAtk"/>
      <set val="1" order="0x08" stat="mAtk"/>
      <set val="8" order="0x08" stat="rCrit"/>
      <add val="0" order="0x10" stat="accCombat"/>
      <set val="379" order="0x08" stat="pAtkSpd"/>
    </for>
  </item>
  <item id="12795" name="Scissors Stick - 30 day limited period">
    <for>
      <set val="1" order="0x08" stat="pAtk"/>
      <set val="1" order="0x08" stat="mAtk"/>
      <set val="8" order="0x08" stat="rCrit"/>
      <add val="0" order="0x10" stat="accCombat"/>
      <set val="379" order="0x08" stat="pAtkSpd"/>
    </for>
  </item>
  <item id="12796" name="Rock Stick - 30 day limited period">
    <for>
      <set val="1" order="0x08" stat="pAtk"/>
      <set val="1" order="0x08" stat="mAtk"/>
      <set val="8" order="0x08" stat="rCrit"/>
      <add val="0" order="0x10" stat="accCombat"/>
      <set val="379" order="0x08" stat="pAtkSpd"/>
    </for>
  </item>
  <item id="12797" name="Paper Stick - 30 day limited period">
    <for>
      <set val="1" order="0x08" stat="pAtk"/>
      <set val="1" order="0x08" stat="mAtk"/>
      <set val="8" order="0x08" stat="rCrit"/>
      <add val="0" order="0x10" stat="accCombat"/>
      <set val="379" order="0x08" stat="pAtkSpd"/>
    </for>
  </item>
  <item id="12798" name="Snowman Transformation Stick">
    <for>
      <set val="1" order="0x08" stat="pAtk"/>
      <set val="1" order="0x08" stat="mAtk"/>
      <set val="8" order="0x08" stat="rCrit"/>
      <add val="0" order="0x10" stat="accCombat"/>
      <set val="379" order="0x08" stat="pAtkSpd"/>
    </for>
  </item>
  <item id="12799" name="Scarecrow Transformation Stick">
    <for>
      <set val="1" order="0x08" stat="pAtk"/>
      <set val="1" order="0x08" stat="mAtk"/>
      <set val="8" order="0x08" stat="rCrit"/>
      <add val="0" order="0x10" stat="accCombat"/>
      <set val="379" order="0x08" stat="pAtkSpd"/>
    </for>
  </item>
</list>
